title: NEO Hackathons
author: NEO Foundation
email: contact@neo.org
description: > # this means to ignore newlines until "twitter_username:"
  We believe that Hackathons and community led competitions can be very helpful 
  for connecting the neo community and developing the neo ecosystem.

# social links
twitter_username: neo_blockchain
github_username:  neo-ngd/Hackathon
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - All.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
